#!/usr/bin/tclsh
# load.tcl

# data file
set psfname psf/PSFID.psf
set xyzname DIR/config.out

# display
display reposition 1000 1500
display resize 680 360
display rendermode GLSL
display depthcue on
display projection orthographic

# background and axes
#display backgroundgradient on
color Display Background gray
axes location off

# graphics window
menu graphics on
menu graphics move 1700 350
menu main move 1700 50

# molecule
mol load psf ${psfname} xyz ${xyzname}
puts "PSF files: ${psfname}"
puts "XYZ files: ${xyzname}"

# create representations for polycations, polyanions & microions
mol modselect 0 0 type 0
mol modcolor 0 0 Charge
mol modmaterial 0 0 Translucent

mol selection type 1
mol addrep 0
mol modcolor 1 0 Charge
mol modmaterial 1 0 Translucent

mol selection type 4
mol addrep 0
mol modcolor 2 0 Charge
mol modmaterial 2 0 Transparent
mol showrep 0 2 off

# style
mol modstyle 0 0 {CPK 0.3 0.1 10}
mol modstyle 1 0 {CPK 0.3 0.1 10}
mol modstyle 2 0 {CPK 0.1 0.3 10}

# bounding box
set bx 2.0
set by 2.0
set bz 16.0

graphics 0 color silver
graphics 0 materials on
graphics 0 material BrushedMetal

graphics 0 line "0.0 0.0 0.0" "0.0 0.0 $bz" width 2
graphics 0 line "0.0 0.0 $bz" "$bx 0.0 $bz" width 2
graphics 0 line "$bx 0.0 $bz" "$bx 0.0 0.0" width 2
graphics 0 line "$bx 0.0 0.0" "0.0 0.0 0.0" width 2

graphics 0 line "0.0 $by 0.0" "0.0 $by $bz" width 2
graphics 0 line "0.0 $by $bz" "$bx $by $bz" width 2
graphics 0 line "$bx $by $bz" "$bx $by 0.0" width 2
graphics 0 line "$bx $by 0.0" "0.0 $by 0.0" width 2

graphics 0 line "0.0 0.0 0.0" "0.0 $by 0.0" width 2
graphics 0 line "0.0 0.0 $bz" "0.0 $by $bz" width 2
graphics 0 line "$bx 0.0 $bz" "$bx $by $bz" width 2
graphics 0 line "$bx 0.0 0.0" "$bx $by 0.0" width 2

# Rotate and sale the scene
rotate y by 100
rotate x by 5
scale by 3

# Save the snapshot
render snapshot FILE.tga

# Quit
quit
